### ISSUE TITLE
[Genshin Impact] after updating the game, the in-game downloads are abnormal

### ISSUE THREAD

**Issue by shoucandanghehe** [neon-nyan/Collapse#166]
![image](https://github.com/neon-nyan/Collapse/assets/51957264/2a9168e0-5a7f-472d-9357-dd7ff75f99d3)

I mentioned it at https://github.com/neon-nyan/Collapse/issues/148#issuecomment-1561150980
And today I reproduced this bug on another PC
Game server: Mainland China
Collapse Version: 1.70.8

Please let me know if there is any information I can provide

**Comment by Cryotechnic** [comment]
Heyo, thanks for submitting an issue! For starters, can you tell us the steps you followed to reproduce this bug, as well as linking the Collapse log for this session (`C:\Users\%username%\AppData\LocalLow\CollapseLauncher\GameFolder\_logs`) ? Thanks!

**Comment by shoucandanghehe** [comment]
i just did
1. Prepare a version 3.6 game
2. Update with Collapse
3. look bug
By the way I just copied the game and now the in-game download is back to 4GB
(Is it possible that this is a bug in the game itself)

[Log-2023-06-09.log](https://github.com/neon-nyan/Collapse/files/11703462/Log-2023-06-09.log)

**Comment by bagusnl** [comment]
seems like its failing to recognize Audio packages from registry and tries to download ja-JP voice instead (CN client usually fallback to default in CN audio).

json parser seems to be failing quite hard
```cs
Schm] [15:19:13.393]  Initializing Region 原神 (Mainland China) Done!
[Warn] [15:19:13.453]  System.Text.Json cannot deserialize language ID registry in this path: 原神
Fallback value will be used (2 / ja-jp).
System.Text.Json.JsonException: The JSON value could not be converted to Hi3Helper.Preset.ServerRegionID. Path: $.selectedServerName | LineNumber: 0 | BytePositionInLine: 131.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String )
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadEnumUsingNamingPolicy(String)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader&, Type, JsonSerializerOptions)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object, ReadStack& , Utf8JsonReader&)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo, Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String , Type, JsonSerializerContext)
   at Hi3Helper.Preset.PresetConfigV2.GetVoiceLanguageID_Genshin(String RegPath) in C:\myGit\Collapse\Hi3Helper.Core\Classes\Preset\Classes\PresetConfigV2.cs:line 226
[Warn] [15:19:13.455]  Error while getting existing GENERAL_DATA_h2389025596 value on 原神 (Mainland China)! Returning value 0 as fallback!
Value: {"deviceUUID":"","userLocalDataVersionId":"0.0.1","deviceLanguageType":2,"deviceVoiceLanguageType":0,"selectedServerName":"cn_gf01","localLevelIndex":0,"deviceID":"","targetUID":"","curAccountName":"","uiSaveData":"{\"currWindowResolutionIndex\":6}","inputData":"{\"scriptVersion\":\"CNRELWin3.7.0\",\"mouseSensitivity\":10.0,\"joypadSenseIndex\":2,\"joypadFocusSenseIndex\":2,\"joypadInvertCameraX\":false,\"joypadInvertCameraY\":false,\"joypadInvertFocusCameraX\":false,\"joypadInvertFocusCameraY\":false,\"mouseSenseIndex\":2,\"mouseFocusSenseIndex\":1,\"touchpadSenseIndex\":2,\"touchpadFocusSenseIndex\":5,\"enableTouchpadFocusAcceleration\":false,\"lastJoypadDefaultScale\":1.0,\"lastJoypadFocusScale\":1.0,\"lastPCDefaultScale\":0.5,\"lastPCFocusScale\":0.4000000059604645,\"lastTouchDefaultScale\":1.0,\"lastTouchFcousScale\":1.0,\"switchWalkRunByBtn\":false,\"skiffCameraAutoFix\":true,\"skiffCameraAutoFixInCombat\":false,\"cameraDistanceRatio\":0.0,\"wwiseVibration\":true,\"isYInited\":true,\"joypadSenseIndexY\":2,\"joypadFocusSenseIndexY\":2,\"mouseSenseIndexY\":2,\"mouseFocusSenseIndexY\":1,\"touchpadSenseIndexY\":2,\"touchpadFocusSenseIndexY\":5,\"lastJoypadDefaultScaleY\":1.0,\"lastJoypadFocusScaleY\":1.0,\"lastPCDefaultScaleY\":0.5,\"lastPCFocusScaleY\":0.4000000059604645,\"lastTouchDefaultScaleY\":1.0,\"lastTouchFcousScaleY\":1.0}","graphicsData":"{\"currentVolatielGrade\":-1,\"customVolatileGrades\":[{\"key\":1,\"value\":2},{\"key\":2,\"value\":3},{\"key\":3,\"value\":2},{\"key\":4,\"value\":2},{\"key\":5,\"value\":2},{\"key\":6,\"value\":5},{\"key\":7,\"value\":2},{\"key\":8,\"value\":3},{\"key\":9,\"value\":1},{\"key\":10,\"value\":1},{\"key\":11,\"value\":1},{\"key\":12,\"value\":2},{\"key\":13,\"value\":2},{\"key\":16,\"value\":1},{\"key\":15,\"value\":2},{\"key\":17,\"value\":5}],\"volatileVersion\":\"CNRELWin3.7.0\"}","globalPerfData":"{\"truePortedFromGraphicData\":true,\"saveItems\":[{\"entryType\":6,\"index\":3,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":13,\"index\":1,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":2,\"index\":3,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":10,\"index\":1,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":5,\"index\":3,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":15,\"index\":2,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":3,\"index\":3,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":9,\"index\":1,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":17,\"index\":3,\"itemVersion\":\"CNRELWin3.1.0\"},{\"index\":2,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":8,\"index\":2,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":4,\"index\":3,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":1,\"index\":1,\"itemVersion\":\"CNRELWin3.1.0\"},{\"entryType\":11,\"index\":0,\"itemVersion\":\"CNRELWin3.1.0\"}],\"portedVersion\":\"CNRELWin3.1.0\",\"portedFromGraphicData\":false}","miniMapConfig":1,"enableCameraSlope":true,"enableCameraCombatLock":true,"completionPkg":false,"completionPlayGoPkg":false,"onlyPlayWithPSPlayer":false,"needPlayGoFullPkgPatch":false,"resinNotification":true,"exploreNotification":true,"volumeGlobal":2,"volumeSFX":10,"volumeMusic":10,"volumeVoice":10,"audioAPI":-1,"audioDynamicRange":0,"audioOutput":0,"_audioSuccessInit":true,"enableAudioChangeAndroidMinimumBufferCapacity":true,"audioAndroidMiniumBufferCapacity":2048,"vibrationLevel":0,"vibrationIntensity":3,"usingNewVibrationSetting":true,"motionBlur":true,"gyroAiming":false,"firstHDRSetting":true,"maxLuminosity":0.0,"uiPaperWhite":0.0,"scenePaperWhite":0.0,"gammaValue":2.200000047683716,"_overrideControllerMapKeyList":[],"_overrideControllerMapValueList":[],"rewiredDisableKeyboard":false,"rewiredEnableKeyboard":false,"rewiredEnableEDS":true,"disableRewiredDelayInit":false,"disableRewiredInitProtection":false,"lastSeenPreDownloadTime":0,"enableEffectAssembleInEditor":true,"forceDisableQuestResourceManagement":false,"needReportQuestResourceDeleteStatusFiles":false,"mtrCached":true,"mtrIsOpen":true,"mtrMaxTTL":32,"mtrTimeOut":5000,"mtrTraceCount":5,"mtrAbortTimeOutCount":3,"mtrAutoTraceInterval":3600,"mtrTraceCDEachReason":600,"mtrTimeInterval":1000,"mtrBanReasons":[],"_customDataKeyList":[],"_customDataValueList":[],"_serializedCodeSwitches":[],"urlCheckCached":true,"urlCheckIsOpen":true,"urlCheckAllIP":false,"urlCheckTimeOut":5000,"urlCheckSueecssTraceCount":5,"urlCheckErrorTraceCount":30,"urlCheckAbortTimeOutCount":3,"urlCheckTimeInterval":1000,"urlCheckCDEachReason":600,"urlCheckBanReasons":[],"mtrUseOldWinVersion":false,"greyTestDeviceUniqueId":""}
System.Text.Json.JsonException: The JSON value could not be converted to Hi3Helper.Preset.ServerRegionID. Path: $.selectedServerName | LineNumber: 0 | BytePositionInLine: 131.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String )
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadEnumUsingNamingPolicy(String)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader&, Type, JsonSerializerOptions)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object, ReadStack& , Utf8JsonReader&)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo, Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String , Type, JsonSerializerContext)
   at Hi3Helper.Preset.PresetConfigV2.GetRegServerNameID() in C:\myGit\Collapse\Hi3Helper.Core\Classes\Preset\Classes\PresetConfigV2.cs:line 326
[Info] [15:19:14.585]  Getting CDN Content from: GitHub at URL: https://github.com/neon-nyan/CollapseLauncher-ReleaseRepo/raw/main/preview/fileindex.json
[Info] [15:19:14.965]  Getting CDN Content from: GitHub at URL: https://github.com/neon-nyan/CollapseLauncher-ReleaseRepo/raw/main/metadata/metadatav2_previewstamp.json
[Info] [14:36:59.124]  Gathering packages information for installation (State: NotInstalled)...
[Info] [14:36:59.129]  Adding segmented package: YuanShen_3.7.0.zip.001 to the list (Hash: dc834ce6ae9dcaa270e8df47ffebc9b3)
[Info] [14:36:59.129]  Adding segmented package: YuanShen_3.7.0.zip.002 to the list (Hash: e75a932291593e7319624849ea0eae5c)
[Info] [14:36:59.129]  Adding segmented package: YuanShen_3.7.0.zip.003 to the list (Hash: 07667eeebda9240d2bb2ad8139488500)
[Info] [14:36:59.129]  Adding segmented package: YuanShen_3.7.0.zip.004 to the list (Hash: aa9acc488bcc361ae25d75dbe6b9dff2)
[Info] [14:36:59.129]  Adding segmented package: YuanShen_3.7.0.zip.005 to the list (Hash: 8174ee47faa8dd5d2d4f9b13dc31ac50)
[Erro] [14:37:01.435]  Cannot save voice language ID: 0 to the registry!
System.Text.Json.JsonException: The JSON value could not be converted to Hi3Helper.Preset.ServerRegionID. Path: $.selectedServerName | LineNumber: 0 | BytePositionInLine: 131.
   at System.Text.Json.ThrowHelper.ThrowJsonException(String )
   at System.Text.Json.Serialization.Converters.EnumConverter`1.ReadEnumUsingNamingPolicy(String)
   at System.Text.Json.Serialization.Converters.EnumConverter`1.Read(Utf8JsonReader&, Type, JsonSerializerOptions)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object, ReadStack& , Utf8JsonReader&)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.Converters.JsonMetadataServicesConverter`1.OnTryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader&, Type, JsonSerializerOptions, ReadStack& , T& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader&, JsonSerializerOptions, ReadStack& )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo, Nullable`1 )
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1, JsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String , Type, JsonSerializerContext)
   at Hi3Helper.Preset.PresetConfigV2.SetVoiceLanguageID_Genshin(Int32 LangID) in C:\myGit\Collapse\Hi3Helper.Core\Classes\Preset\Classes\PresetConfigV2.cs:line 274
   ```

**Comment by Cryotechnic** [comment]
Fixed in b1ee4a9. Keeping this issue open for tracking until v1.70.X release. Thank you for your report!

**Comment by shoucandanghehe** [comment]
![image](https://github.com/neon-nyan/Collapse/assets/51957264/bb27940d-f536-4850-b38b-6b59c6976cd4)
Looks like this bug is not fixed
I made a backup of the game with the bug, I can upload it if needed
[log-2023-04-12.log](https://github.com/neon-nyan/Collapse/files/11954218/log-2023-04-12.log)

**Comment by bagusnl** [comment]
Wait, I'm confused, so is this with which version of Collapse?

**Comment by shoucandanghehe** [comment]
> Wait, I'm confused, so is this with which version of Collapse?

It's 1.70.8 because I forgot to update (I thought it was the latest
I will try to reproduce it on the latest version (provided that I find the archive of the old game

**Comment by bagusnl** [comment]
We'll try to analyze the bug with the log you provided. Though we are sorry that we can't fix this faster because it seems that you are on CN client, which we don't have an access to. But we'll try, thanks for reporting !

**Comment by bagusnl** [comment]
While at it, can you send exported registry file from `Computer\HKEY_CURRENT_USER\Software\miHoYo\原神` also this file `YuanShen_Data\Persistent\audio_lang_14` ?

Do this before you press the update game OR after you're done and pass the downloading page.

As the registry file has some sensitive data in it, you can directly email them to me over at bagusnl@protonmail.com or if you prefer to redact them yourself you can delete these registries from the EXPORTED file:
- MIHOYO_SDK_ADL*
- MIHOYO_SDK_DEVICE_FP

**Comment by gablm** [comment]
This bug or similar has also happened to me. (Preview 1.71.2)

It just skips all of the audio files with this error.
![image](https://github.com/neon-nyan/Collapse/assets/44784408/ebb9bb8c-6ae5-483c-999e-23f88941b4f9)

**Comment by shoucandanghehe** [comment]
In the 4.0 update, I ran into another 9.6G in-game download, and as a comparison, the official launcher update is only 380M.
I checked the game log and found these
```
[Game] [2023-08-16 09:18:51.234] IsBaseResVersionHashChanged=> baseResVersionHashInPersist = a6efe3d94696ed3732ea3377da239a1b, md5 in streamingResVersion = 31e2daf050c263f4a1f9718ff152c4b0
[Game] UnityEngine.Logger:LogFormat(LogType, String, Object[])
[Game] UnityEngine.Debug:LogFormat(String, Object[])
[Game] KECDHHJDDKL:ACPCFABGJKK()
[Game] KECDHHJDDKL:PLFAMIMOOFE()
[Game] MoleMole.GameManager:CHEELKMADOM()
[Game]
[Game] (Filename: D:\WKSPC\4.0Fix\sourceCode\artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 64)
[Game] [20-23-08] [20-23-08] [20-23-08] [20-23-08
[Game] [2023-08-16 09:18:51.234] Package has changed!!!!! Clear state files in persist dir!!!!!
[Game] UnityEngine.Logger:Log(LogType, Object)
[Game] UnityEngine.Debug:LogWarning(Object)
[Game] KECDHHJDDKL:PLFAMIMOOFE()
[Game] MoleMole.GameManager:CHEELKMADOM()
```
Launcher version: 1.71.6
Launcher log: [log-2023-08-16-pre1.71.6-id1.log](https://github.com/neon-nyan/Collapse/files/12354349/log-2023-08-16-pre1.71.6-id1.log)

If you need the full game log please talk to me.
By the way I keep a backup of the old game and can provide a copy or I'll do the test.
~~But should I open a new issue?~~ @bagusnl

**Comment by bagusnl** [comment]
No, lets keep discussing it here, did you have entire collapse console still open? If you have please copy them here

**Comment by shoucandanghehe** [comment]
It's still on but some of the logs are drowned out by the game logs

**Comment by bagusnl** [comment]
When is the last time you open the game on that instance?

**Comment by shoucandanghehe** [comment]
After saving the log above
And here's the full log of the first time open the game after the update
[Game.log](https://github.com/neon-nyan/Collapse/files/12354524/Game.log)

**Comment by bagusnl** [comment]
I meant before updating the game

**Comment by shoucandanghehe** [comment]
The night before the update
